name: Laravel Deployment
on:
    push:
        branches:
            - develop
            - main

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Deploy to development
              if: github.ref == 'refs/heads/develop'
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: "${{ secrets.DEV_HOST }}"
                  username: "${{ secrets.DEV_USERNAME }}"
                  password: "${{ secrets.DEV_PASSWORD }}"
                  port: "${{ secrets.DEV_PORT }}"
                  script: |
                      cd /var/www/alumwork
                      git fetch origin
                      git reset --hard origin/develop
                      git clean -fd 
                      git pull origin develop --force 
                      composer install --no-interaction --prefer-dist --optimize-autoloader
                      cd public/themes/sage 
                      composer install --no-interaction --prefer-dist --optimize-autoloader
                      npm install
                      npm run build

            - name: Deploy to production
              if: github.ref == 'refs/heads/main'
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: "${{ secrets.PROD_HOST }}"
                  username: "${{ secrets.PROD_USERNAME }}"
                  password: "${{ secrets.PROD_PASSWORD }}"
                  script: |
                      cd /alumwork.de/httpdocs
                      git fetch origin
                      git reset --hard origin/main
                      git clean -fd 
                      git pull origin main --force

            - name: Send Telegram message
              if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
              uses: appleboy/telegram-action@v0.1.0
              with:
                  to: "${{ secrets.TELEGRAM_ID }}"
                  token: "${{ secrets.TELEGRAM_TOKEN }}"
                  message: |
                      Deployment successful https://alumwork.de/ on branch ${{ github.ref }}